services:
  - type: web
    name: dflex
    runtime: python
    buildCommand: pip install -r requirements.txt && npm --prefix client install && npm --prefix client run build
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
